# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class Menu_Ui_Form(object):

    def setupUi(self, Form):
        Form.setObjectName("Menu")
        Form.resize(800, 600)

        self.label = QLabel(Form)
        self.label.setGeometry(QtCore.QRect(250, 70, 350, 41))

        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(250, 180, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.resize(300, 100)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 370, 111, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.resize(300, 100)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Menu", "Menu"))
        self.pushButton.setText(_translate("Menu", "Image"))
        self.pushButton.setFont(QFont('Image', 20))
        self.pushButton_2.setText(_translate("Menu", "WebCam"))
        self.pushButton_2.setFont(QFont('WebCam', 20))
        self.label.setText(_translate("Menu", "Choose image or video"))
        self.label.setFont(QFont('Choose image or video', 16))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Menu_Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
